  # syntax=docker/dockerfile:1
  FROM ruby:3.3.6-slim

  WORKDIR /rails

  RUN apt-get update -qq && \
      apt-get install --no-install-recommends -y curl libjemalloc2 libvips postgresql-client build-essential git libpq-dev pkg-config && \
      rm -rf /var/lib/apt/lists /var/cache/apt/archives

  # Copiar Gemfile e instalar as gems
  COPY Gemfile Gemfile.lock ./
  RUN bundle install

  # Copiar código do app
  COPY . .

  # Expor a porta do Rails
  EXPOSE 3000

  CMD ["bash", "-c", "bin/rails db:prepare && bin/dev"]
