services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game_of_life_extendi_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/game_of_life_extendi_development
    ports:
      - "3000:3000"
      - "8808:8808"
    depends_on:
      - db
    volumes:
      - .:/rails
    tty: true
    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      bundle check || bundle install &&
      yard server --host 0.0.0.0 --port 8808 &
      bin/dev"
volumes:
  postgres_data:
