version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "game_of_life_extendi_${RAILS_ENV:-development}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: "${RAILS_ENV:-development}"
    environment:
      RAILS_ENV: "${RAILS_ENV:-development}"
      DATABASE_URL: "postgres://postgres:password@db:5432/game_of_life_extendi_${RAILS_ENV:-development}"
    depends_on:
      - db
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    tty: true
    # Se quiser usar o estágio de 'development', basta não setar RAILS_ENV=production
    # e a imagem usará o CMD do estágio "development".
    # Abaixo, você pode sobrescrever para rodar outro comando, se quiser:
    command: >
      bash -c "rm -f tmp/pids/server.pid && bin/rails db:create db:migrate && bin/rails s -b 0.0.0.0 -p 3000"

volumes:
  postgres_data:
